CREATE DATABASE FoodProject;
GO

USE FoodProject;
GO

CREATE TABLE TAIKHOAN (
    ID_TAIKHOAN INT IDENTITY PRIMARY KEY,
    MATKHAU NVARCHAR(255) NOT NULL,
    VAITRO NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE -- Thêm thuộc tính email để phục vụ đăng nhập/ đăng ký
);

CREATE TABLE CUAHANG (
    ID_CUAHANG INT IDENTITY PRIMARY KEY,
    ID_TAIKHOAN INT,
    TENCUAHANG NVARCHAR(255),
    DIACHI NVARCHAR(255),
    SDT NVARCHAR(15),
    DOANHTHU DECIMAL(12,2) DEFAULT 0,
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE KHACHHANG (
    ID_KHACHHANG INT IDENTITY PRIMARY KEY,
    ID_TAIKHOAN INT,
    HOTEN NVARCHAR(255),
    NGAYSINH DATE,
    DIACHI NVARCHAR(255),
    SDT NVARCHAR(15),
    -- Xóa thuộc tính TIEN
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE SHIPPER (
    ID_SHIPPER INT IDENTITY PRIMARY KEY,
    ID_TAIKHOAN INT,
    HOTEN NVARCHAR(255),
    NGAYSINH DATE,
    SDT NVARCHAR(15),
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE LOAIMONAN (
    ID_LOAI INT IDENTITY PRIMARY KEY,
    TENLOAI NVARCHAR(255),
    IMG NVARCHAR(255)   -- Đổi kiểu cho IMG thành String để chứa link của ảnh
);

CREATE TABLE MONAN (
    ID_MONAN INT IDENTITY PRIMARY KEY,
    ID_CUAHANG INT,
    ID_LOAI INT,
    TENMON NVARCHAR(255),
    TRANGTHAI NVARCHAR(50)
        CHECK (TRANGTHAI IN (N'con_ban', N'het_hang', N'ngung_kinh_doanh')),
    GIA DECIMAL(10,2),
    IMG NVARCHAR(255),  -- Thêm thuộc tính IMG kiểu String cho bảng MONAN
    FOREIGN KEY (ID_CUAHANG) REFERENCES CUAHANG(ID_CUAHANG),
    FOREIGN KEY (ID_LOAI) REFERENCES LOAIMONAN(ID_LOAI)
);

CREATE TABLE GIOHANG (
    ID_GIOHANG INT IDENTITY PRIMARY KEY,
    ID_KHACHHANG INT,
    TRANGTHAI NVARCHAR(50)
        CHECK (TRANGTHAI IN (N'dang_tao', N'da_dat', N'da_huy')),
    TONGTIEN DECIMAL(12,2) DEFAULT 0,
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG)
);

CREATE TABLE GIOHANG_MONAN (
    ID_GIOHANG INT,
    ID_MONAN INT,
    SOLUONG INT,
    PRIMARY KEY (ID_GIOHANG, ID_MONAN),
    FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG),
    FOREIGN KEY (ID_MONAN) REFERENCES MONAN(ID_MONAN)
);

CREATE TABLE VOUCHER (
    ID_VOUCHER INT IDENTITY PRIMARY KEY,
    ID_KHACHHANG INT,
    LOAIVOUCHER NVARCHAR(100),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG)
);

CREATE TABLE DONHANG (
    ID_DONHANG INT IDENTITY PRIMARY KEY,
    ID_GIOHANG INT,
    ID_KHACHHANG INT,
    ID_SHIPPER INT,
    ID_VOUCHER INT,
    THOIGIANDAT DATETIME,
    TRANGTHAI NVARCHAR(50)
        CHECK (TRANGTHAI IN (N'cho_xac_nhan', N'dang_giao', N'da_giao', N'da_huy')),
    TONGTIEN DECIMAL(12,2),
    PHUONGTHUCTHANHTOAN NVARCHAR(50),
    FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG),
    FOREIGN KEY (ID_SHIPPER) REFERENCES SHIPPER(ID_SHIPPER),
    FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER(ID_VOUCHER)
);

-- Trigger
CREATE TRIGGER trg_UpdateCartTotal
    ON GIOHANG_MONAN
    AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    -- Tránh việc trả về các thông báo "x rows affected" làm nhiễu JDBC của Java
    SET NOCOUNT ON;

    -- Cập nhật TONGTIEN cho các giỏ hàng có sự thay đổi (thêm, sửa hoặc xóa món)
UPDATE GIOHANG
SET TONGTIEN = ISNULL((
                          SELECT SUM(m.GIA * gm.SOLUONG)
                          FROM GIOHANG_MONAN gm
                                   JOIN MONAN m ON gm.ID_MONAN = m.ID_MONAN
                          WHERE gm.ID_GIOHANG = GIOHANG.ID_GIOHANG
                      ), 0)
WHERE ID_GIOHANG IN (
    -- Lấy danh sách ID_GIOHANG từ bảng ảo 'inserted' (khi thêm/sửa)
    SELECT ID_GIOHANG FROM inserted
    UNION
    -- Lấy danh sách ID_GIOHANG từ bảng ảo 'deleted' (khi xóa/sửa)
    SELECT ID_GIOHANG FROM deleted
);
END;