CREATE DATABASE IF NOT EXISTS online_food
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE online_food;

CREATE TABLE TAIKHOAN (
    ID_TAIKHOAN INT AUTO_INCREMENT PRIMARY KEY,
    MATKHAU VARCHAR(255) NOT NULL,
    VAITRO VARCHAR(50) NOT NULL
);

CREATE TABLE CUAHANG (
    ID_CUAHANG INT AUTO_INCREMENT PRIMARY KEY,
    ID_TAIKHOAN INT,
    TENCUAHANG VARCHAR(255),
    DIACHI VARCHAR(255),
    SDT VARCHAR(15),
    DOANHTHU DECIMAL(12,2) DEFAULT 0,
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE KHACHHANG (
    ID_KHACHHANG INT AUTO_INCREMENT PRIMARY KEY,
    ID_TAIKHOAN INT,
    HOTEN VARCHAR(255),
    NGAYSINH DATE,
    DIACHI VARCHAR(255),
    SDT VARCHAR(15),
    TIEN DECIMAL(12,2) DEFAULT 0,
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE SHIPPER (
    ID_SHIPPER INT AUTO_INCREMENT PRIMARY KEY,
    ID_TAIKHOAN INT,
    HOTEN VARCHAR(255),
    NGAYSINH DATE,
    SDT VARCHAR(15),
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE LOAIMONAN (
    ID_LOAI INT AUTO_INCREMENT PRIMARY KEY,
    TENLOAI VARCHAR(255),
    IMG BLOB
);

CREATE TABLE MONAN (
    ID_MONAN INT AUTO_INCREMENT PRIMARY KEY,
    ID_CUAHANG INT,
    ID_LOAI INT,
    TENMON VARCHAR(255),
    TRANGTHAI ENUM('còn bán','hết hàng'),
    GIA DECIMAL(10,2),
    FOREIGN KEY (ID_CUAHANG) REFERENCES CUAHANG(ID_CUAHANG),
    FOREIGN KEY (ID_LOAI) REFERENCES LOAIMONAN(ID_LOAI)
);

CREATE TABLE GIOHANG (
    ID_GIOHANG INT AUTO_INCREMENT PRIMARY KEY,
    ID_KHACHHANG INT,
    TRANGTHAI ENUM('đang tạo','đã đặt'),
    TONGTIEN DECIMAL(12,2) DEFAULT 0,
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG)
);

CREATE TABLE GIOHANG_MONAN (
    ID_GIOHANG INT,
    ID_MONAN INT,
    SOLUONG INT,
    PRIMARY KEY (ID_GIOHANG, ID_MONAN),
    FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG),
    FOREIGN KEY (ID_MONAN) REFERENCES MONAN(ID_MONAN)
);

CREATE TABLE VOUCHER (
    ID_VOUCHER INT AUTO_INCREMENT PRIMARY KEY,
    ID_KHACHHANG INT,
    LOAIVOUCHER ENUM('free ship', 'giảm 10%','giảm 20%', 'giảm 50%'),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG)
);

CREATE TABLE DONHANG (
    ID_DONHANG INT AUTO_INCREMENT PRIMARY KEY,
    ID_GIOHANG INT,
    ID_KHACHHANG INT,
    ID_SHIPPER INT,
    ID_VOUCHER INT,
    THOIGIANDAT DATETIME,
    TRANGTHAI ENUM('chờ giao','đang giao','đã_giao'),
    TONGTIEN DECIMAL(12,2),
    PHUONGTHUCTHANHTOAN VARCHAR(50),
    FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG),
    FOREIGN KEY (ID_SHIPPER) REFERENCES SHIPPER(ID_SHIPPER),
    FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER(ID_VOUCHER)
);