CREATE DATABASE FoodProject;
GO

USE FoodProject;
GO

CREATE TABLE TAIKHOAN (
    ID_TAIKHOAN INT IDENTITY PRIMARY KEY,
    MATKHAU NVARCHAR(255) NOT NULL,
    VAITRO NVARCHAR(50) NOT NULL CHECK (VAITRO IN (N'Khách hàng', N'Cửa hàng', N'Shipper', N'Admin')),
    EMAIL NVARCHAR(255) NOT NULL UNIQUE -- Thêm thuộc tính email để phục vụ đăng nhập/ đăng ký
);

CREATE TABLE CUAHANG (
    ID_CUAHANG INT IDENTITY PRIMARY KEY,
    ID_TAIKHOAN INT NOT NULL UNIQUE,
    TENCUAHANG NVARCHAR(255),
    DIACHI NVARCHAR(255),
    SDT NVARCHAR(15),
    DOANHTHU DECIMAL(12,2) DEFAULT 0,
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE KHACHHANG (
    ID_KHACHHANG INT IDENTITY PRIMARY KEY,
    ID_TAIKHOAN INT NOT NULL UNIQUE,
    HOTEN NVARCHAR(255),
    NGAYSINH DATE,
    DIACHI NVARCHAR(255),
    SDT NVARCHAR(15),
    -- Xóa thuộc tính TIEN
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE SHIPPER (
    ID_SHIPPER INT IDENTITY PRIMARY KEY,
    ID_TAIKHOAN INT NOT NULL UNIQUE,
    HOTEN NVARCHAR(255),
    NGAYSINH DATE,
    SDT NVARCHAR(15),
    FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN)
);

CREATE TABLE LOAIMONAN (
    ID_LOAI INT IDENTITY PRIMARY KEY,
    TENLOAI NVARCHAR(255),
    IMG NVARCHAR(255)   -- Đổi kiểu cho IMG thành String để chứa link của ảnh
);

CREATE TABLE MONAN (
    ID_MONAN INT IDENTITY PRIMARY KEY,
    ID_CUAHANG INT,
    ID_LOAI INT,
    TENMON NVARCHAR(255),
    TRANGTHAI NVARCHAR(50)
        CHECK (TRANGTHAI IN (N'Còn hàng', N'Hết hàng')),
    GIA DECIMAL(10,2) CHECK(GIA >= 0),
    IMG NVARCHAR(255),  -- Thêm thuộc tính IMG kiểu String cho bảng MONAN
    FOREIGN KEY (ID_CUAHANG) REFERENCES CUAHANG(ID_CUAHANG),
    FOREIGN KEY (ID_LOAI) REFERENCES LOAIMONAN(ID_LOAI)
);

CREATE TABLE GIOHANG (
    ID_GIOHANG INT IDENTITY PRIMARY KEY,
    ID_KHACHHANG INT NOT NULL,
    TRANGTHAI NVARCHAR(50)
        CHECK (TRANGTHAI IN (N'Đang tạo', N'Đã đặt', N'Đã hủy')),
    TONGTIEN DECIMAL(12,2) DEFAULT 0 CHECK(TONGTIEN >= 0),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG)
);

CREATE TABLE GIOHANG_MONAN (
    ID_GIOHANG INT,
    ID_MONAN INT,
    SOLUONG INT CHECK(SOLUONG > 0),
    PRIMARY KEY (ID_GIOHANG, ID_MONAN),
    FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG),
    FOREIGN KEY (ID_MONAN) REFERENCES MONAN(ID_MONAN)
);

CREATE TABLE VOUCHER (
    ID_VOUCHER INT IDENTITY PRIMARY KEY,
    ID_KHACHHANG INT,
    LOAIVOUCHER NVARCHAR(100) CHECK(LOAIVOUCHER IN(N'Freeship', N'-10%', N'-30%', N'-50%', N'-70%')),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG)
);

CREATE TABLE DONHANG (
    ID_DONHANG INT IDENTITY PRIMARY KEY,
    ID_GIOHANG INT UNIQUE,
    ID_KHACHHANG INT,
    ID_SHIPPER INT,
    ID_VOUCHER INT,
    THOIGIANDAT DATETIME DEFAULT GETDATE(),
    TRANGTHAI NVARCHAR(50)
        CHECK (TRANGTHAI IN (N'Chờ xác nhận', N'Đang giao', N'Đã giao', N'Đã hủy')),
    TONGTIEN DECIMAL(12,2) CHECK(TONGTIEN >= 0),
    PHUONGTHUCTHANHTOAN NVARCHAR(50),
    FOREIGN KEY (ID_GIOHANG) REFERENCES GIOHANG(ID_GIOHANG),
    FOREIGN KEY (ID_KHACHHANG) REFERENCES KHACHHANG(ID_KHACHHANG),
    FOREIGN KEY (ID_SHIPPER) REFERENCES SHIPPER(ID_SHIPPER),
    FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER(ID_VOUCHER)
);